
var pike = { //Condenced name for variable
    name: '1st and Pike', //real-english name
    minCust: 23, //Minimum Customers per Hour
    maxCust: 65, //Maximum Customers per Hour
    avgCookiesPerCust: 6.3, //The average number of cookies each customer purchases
    custPerHour: [], //generate a random number of customer per hour based on the minimum and maximum number of customers per hour
    cookiesPerHour: [], //Number of cookies sold based on the number of customers that hour * the average number of cookies sold to each customer
    hoursOfOps: ['6a', '7a', '8a', '9a', '10a', '11a', '12p', '1p', '2p','3p', '4p', '5p', '6p', '7p', '8p'], //Array of the hours of opperation
    dailyTotal: 0, //Total number of sales generated by adding each hour individually to each other to create a sum
    generateRandomCustPerHour: function(min, max) { //generates a function called generateRandomCustPerHour with a place holder for min and max
        for(var i = 0; i < this.hoursOfOps.length; i++) { //generate a for loop
            var randomCust = Math.floor(Math.random() * (max - min + 1) + min); //generate the math for the random number of customers for each hour.  The Math.floor call doesn't include the min number.  Math.random then generates a number between 0 and 0.99999999....
        }
    },
    generateHourlySales: function() {
        //Line blow will populate custPerHour array
        this.generateRandomCustPerHour(this.minCust, this.maxCust);

        for(var i = 0; i < this.hoursOfOps.length; i++) {
            var perHour = Math.round(this.custPerHour[i] * this.avgCookiesPerCust);
            this.cookiesPerHour.push(perHour);

            this.dailyTotal += perHour;
        }
    },
    render: function() {
        //Line below will generate hourly sales, which also generates customers per hour
        this.generateHourlySales();
        //this.hoursOfOps = ['6a', '7a', '8a']
        //this.custPerHour = [24, ]
        //this.cookiesPerHour = []

        var mainEl = document.getElementById('main-content');
        var containerEl = document.createElement('section');

        var headingEl = document.createElement('h3');
        headingEl.textContent = this.name;
        containerEl.appendChild(headingEl);

        var ulEl = document.cr4eeateElement('ul');

        for(var i = 0; i < this.hoursOfOps.length; i++) {
            var liEl = document.createElement('li');
            liEl.textContent = `${this.hoursOfOps[i]}: ${this.cookiesPerHour[i]} cookies`;
            ulEl.appendChild(liEl);
        },

        var totalEl = document.createElement(li);
        totalEl.textContent = `Total: ${this.dailyTotal} cookies`
    },
};

/*
var locSales = ['pike', 'seaTac', 'seaCenter', 'capHill', 'alki'];
var hr = ['8am', '9am', '10am', '11am', '12pm', '1pm', '2pm', '3pm', '4pm', '5pm', '6pm', '7pm', '8pm'];
var locIndex = 0;
var hrIndex = 0;
var hrSales;


var pike = {
	locName: '1st and Pike',
	minCust: 23,
	maxCust: 65,
	avgCook: 6.3,
	cust: Math.floor(Math.random()*(this.maxCust - this.minCust) + this.minCust),
	cookSold: Math.round(this.Cust * this.avgCook),

  cookies: function() {
    return `${this.cookSold}`;
	},
	render: function() {
		var container = document.createElement('th');
    var tableEL = document.getElementById('cookie-spread');

    tableEL.textContent = this.cookSold;

    container.appendChild(tableEL);



    //tableEL.appendChild(container);
	},
};

pike.cookies();
pike.render();
console.log(pike.cust);
console.log(pike.CookSold);

/*var Cust =Math.floor(Math.random()*(pike.maxCust - pike.minCust) + pike.minCust);
var CookSold = Math.round(Cust * pike.avgCook);
console.log(Cust);
console.log(CookSold);

var seaTac = {
	locName: 'SeaTac Airport',
	minCust: 3,
	maxCust: 24,
	avgCook: 1.2,
};

var seaCent = {
	locName: 'Seattle Center',
	minCust: 11,
	maxCust: 38,
	avgCook: 3.7,
};

var capHill = {
	locName: 'Capital Hill',
	minCust: 20,
	maxCust: 38,
	avgCook: 2.3,
};

var alki = {
	locName: 'Alki',
	minCust: 2,
	maxCust: 16,
	avgCook: 4.6,
};

/*
function cookieSales() {
	for(var i = 0; i < locSales.length; i++) {
		for(var j = 0; j < hr.length; j++) {
			var Cust = Math.floor(Math.random()*(locSales[i].maxCust - locSales[i].minCust) + locSales[i].minCust);
			var CookSold = Math.round(Cust * locSales[i].avgCook);
			console.log(Cust);
			console.log(CookSold);
		}
	}
}
cookieSales();


/*
var Cust = Math.floor(Math.random()*(pike.maxCust - pike.minCust) + pike.minCust);
var CookSold = Math.round(Cust * pike.avgCook);
console.log(Cust);
console.log(CookSold);



function hrSales(locName, minCust, maxCust, avgCook) {
	this.locName = locName;
	this.minCust = minCust;
	this,maxCust = maxCust;
	this.avgCook = avgCook;

};




}

var locSales = ['1st and Pike', 'SeaTac Airport', 'Seattle Center', 'Capitol Hill', 'Alki'];
var hr = ['8am', '9am', '10am', '11am', '12pm', '1pm', '2pm', '3pm', '4pm', '5pm', '6pm', '7pm', '8pm'];
var minCust = [23, 3, 11, 20, 2];
var maxCust = [65, 24, 38,38,16];
var avgCook = [6.3, 1.2, 3.7, 2.3, 4.6];

var hrIndex;
var locIndex;
var hrSales;

for(locIndex = 0; locIndex < locSales.length; locIndex++) {
    for(hrIndex = 0; hrIndex < minCust.length; hrIndex++) {
        var numCust = numCust(random(minCust[hrIndex], maxCust[hrIndex]));
        hrSales = numCust * avgCook[hrIndex];
    }
}
*/