
var pikeAndFirst = { //Condenced name for variable
    name: 'First and Pike', //real-english name
    minCustPerHour: 23, //Minimum Customers per Hour
    maxCustPerHour: 65, //Maximum Customers per Hour
    avgCookiesPerCust: 6.3, //The average number of cookies each customer purchases
    custPerHour: [], //generate a random number of customer per hour based on the minimum and maximum number of customers per hour
    cookiesPerHour: [], //Number of cookies sold based on the number of customers that hour * the average number of cookies sold to each customer
    hoursOfOps: ['6a', '7a', '8a', '9a', '10a', '11a', '12p', '1p', '2p','3p', '4p', '5p', '6p', '7p', '8p'], //Array of the hours of opperation
    dailyTotal: 0, //Total number of sales generated by adding each hour individually to each other to create a sum
    generateRandomCustPerHour: function(min, max) { //generates a function called generateRandomCustPerHour with a place holder for min and max
        for(var i = 0; i < this.hoursOfOps.length; i++) { //generate a for loop
            var randomCust = Math.floor(Math.random() * (max - min + 1) + min); //generate the math for the random number of customers for each hour.  The Math.floor call doesn't include the min number.  Math.random then generates a number between 0 and 0.99999999....
        }
    },
    generateHourlySales: function() {
        //Line blow will populate custPerHour array
        this.generateRandomCustPerHour(this.minCustPerHour, this.maxCustPerHour);

        for(var i = 0; i < this.hoursOfOps.length; i++) {
            var perHour = Math.round(this.custPerHour[i] * this.avgCookiesPerCust);
            this.cookiesPerHour.push(perHour);

            this.dailyTotal += perHour;
        }
    },
    render: function() {
        //Line below will generate hourly sales, which also generates customers per hour
        this.generateHourlySales();
        //this.hoursOfOps = ['6a', '7a', '8a']
        //this.custPerHour = [24, ]
        //this.cookiesPerHour = []

        var mainEl = document.getElementById('main-content');
        var containerEl = document.createElement('section');

        var headingEl = document.createElement('h3');
        headingEl.textContent = this.name;
        containerEl.appendChild(headingEl);

        var ulEl = document.cr4eeateElement('ul');

        for(var i = 0; i < this.hoursOfOps.length; i++) {
            var liEl = document.createElement('li');
            liEl.textContent = `${this.hoursOfOps[i]}: ${this.cookiesPerHour[i]} cookies`;
            ulEl.appendChild(liEl);
        },

        var totalEl = document.createElement(li);
        totalEl.textContent = `Total: ${this.dailyTotal} cookies`
    },
};